// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NordigenService.EntityFramework;

#nullable disable

namespace NordigenService.Migrations
{
    [DbContext(typeof(TransactionsContext))]
    partial class TransactionsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("NordigenService.EntityFramework.TransactionEntity", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditorBban")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditorIban")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("DebtorBban")
                        .HasColumnType("TEXT");

                    b.Property<string>("DebtorIban")
                        .HasColumnType("TEXT");

                    b.Property<string>("DebtorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndToEndId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemittanceInformationUnstructured")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
